- project:
    name: openstack/tap-as-a-service
    check:
      jobs:
        - tap-as-a-service-tempest-dsvm
    gate:
      jobs:
        - tap-as-a-service-tempest-dsvm

- job:
    name: tap-as-a-service-tempest-dsvm
    parent: legacy-dsvm-base
    run: playbooks/legacy/tempest-dsvm-tap-as-a-service/run.yaml
    post-run: playbooks/legacy/tempest-dsvm-tap-as-a-service/post.yaml
    timeout: 7800
    required-projects:
      - openstack-infra/devstack-gate
      - openstack/tap-as-a-service
      - openstack/tap-as-a-service-tempest-plugin
      - openstack/tempest
    irrelevant-files:
      - ^(test-|)requirements.txt$
      - ^.*\.rst$
      - ^doc/.*$
      - ^neutron_taas/tests/unit/.*$
      - ^setup.cfg$
      - ^specs/.*$
